/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteImport } from './routes/session'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIndexRouteImport } from './routes/session/index'
import { Route as SessionListRouteImport } from './routes/session/list'
import { Route as SessionJoinRouteImport } from './routes/session/join'
import { Route as SessionCreateRouteImport } from './routes/session/create'
import { Route as MapSessionIdRouteImport } from './routes/map.$sessionId'

const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIndexRoute = SessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionRoute,
} as any)
const SessionListRoute = SessionListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => SessionRoute,
} as any)
const SessionJoinRoute = SessionJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => SessionRoute,
} as any)
const SessionCreateRoute = SessionCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SessionRoute,
} as any)
const MapSessionIdRoute = MapSessionIdRouteImport.update({
  id: '/map/$sessionId',
  path: '/map/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/session': typeof SessionRouteWithChildren
  '/map/$sessionId': typeof MapSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/session/join': typeof SessionJoinRoute
  '/session/list': typeof SessionListRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map/$sessionId': typeof MapSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/session/join': typeof SessionJoinRoute
  '/session/list': typeof SessionListRoute
  '/session': typeof SessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/session': typeof SessionRouteWithChildren
  '/map/$sessionId': typeof MapSessionIdRoute
  '/session/create': typeof SessionCreateRoute
  '/session/join': typeof SessionJoinRoute
  '/session/list': typeof SessionListRoute
  '/session/': typeof SessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/session'
    | '/map/$sessionId'
    | '/session/create'
    | '/session/join'
    | '/session/list'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map/$sessionId'
    | '/session/create'
    | '/session/join'
    | '/session/list'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/session'
    | '/map/$sessionId'
    | '/session/create'
    | '/session/join'
    | '/session/list'
    | '/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionRoute: typeof SessionRouteWithChildren
  MapSessionIdRoute: typeof MapSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/': {
      id: '/session/'
      path: '/'
      fullPath: '/session/'
      preLoaderRoute: typeof SessionIndexRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/list': {
      id: '/session/list'
      path: '/list'
      fullPath: '/session/list'
      preLoaderRoute: typeof SessionListRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/join': {
      id: '/session/join'
      path: '/join'
      fullPath: '/session/join'
      preLoaderRoute: typeof SessionJoinRouteImport
      parentRoute: typeof SessionRoute
    }
    '/session/create': {
      id: '/session/create'
      path: '/create'
      fullPath: '/session/create'
      preLoaderRoute: typeof SessionCreateRouteImport
      parentRoute: typeof SessionRoute
    }
    '/map/$sessionId': {
      id: '/map/$sessionId'
      path: '/map/$sessionId'
      fullPath: '/map/$sessionId'
      preLoaderRoute: typeof MapSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessionRouteChildren {
  SessionCreateRoute: typeof SessionCreateRoute
  SessionJoinRoute: typeof SessionJoinRoute
  SessionListRoute: typeof SessionListRoute
  SessionIndexRoute: typeof SessionIndexRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionCreateRoute: SessionCreateRoute,
  SessionJoinRoute: SessionJoinRoute,
  SessionListRoute: SessionListRoute,
  SessionIndexRoute: SessionIndexRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionRoute: SessionRouteWithChildren,
  MapSessionIdRoute: MapSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
